### PR TITLE
Adjust typography colors to match with designs in zeplin

### PR DESCRIPTION
**Pull request by jaroslav-kubicek**
This Pull Request meets the following criteria:

* [x] Tests have been added/adjusted for my new feature
* [x] New Components are registered in index.js of my project

### CODE REVIEW

**Comment by git-toni** [comment]
What about `#bac7d5` as seen in the phone number here https://app.zeplin.io/project/5a859818a44a3c0f897647b1/screen/5a859854fa58306029cc9a3a
 or in this input text https://app.zeplin.io/project/5a859818a44a3c0f897647b1/screen/5a859857965a0650b0ed4dbe?

**Comment by jaroslav-kubicek** [comment]
I would introduce it as "input"?

**Comment by jaroslav-kubicek** [comment]
I've created https://github.com/kiwicom/react-kiwi-ui/pull/34 with separated constants so they can be used outside of Typography as well

**Comment by Fallion** [comment]
Referencing this in #35

**Pull request merged**
